// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace appTest
{
	public partial class CartViewController : UIViewController
	{
		public CartViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
