// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace appTest
{
	public partial class CatalogViewController : UIViewController
	{
		public CatalogViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
