// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace appTest
{
	public partial class ProfileViewController : UIViewController
	{
		public ProfileViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
