// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace appTest
{
	public partial class UmbracoViewController : UIViewController
	{
		public UmbracoViewController (IntPtr handle) : base (handle)
		{
		}

		public Cart Kurv = new Cart();

		public Product Vinkelnøglesæt = new Product(1, "Vinkelnøglesæt", null, null, 45, 10);



		partial void AddToCartBtn(Foundation.NSObject sender)
        {
			price.Text = "test";
            Console.WriteLine("ok");

			Kurv.Varer.Add(Vinkelnøglesæt);

		}

		


	}


}
